version: 2

sources:
  - name: silverscreen
    database: SILVER_SCREEN
    schema: RAW
    tables:
      - name: MOVIE_CATALOGUE
      - name: INVOICES
      - name: NJ_001
      - name: NJ_002
      - name: NJ_003
